### ISSUE TITLE
Chyba pri definici Routes

### ISSUE THREAD

**Issue by michalpixel** [ipublikuj/websockets#13]
Zdravim,
mam problem pri definovani rout... pokud postupuji podle navodu, obdrzim tuto chybu...

```
webSockets:
	routes:
		'/chat/<room>' : 'Chat:'
		'/notification' : 'Notification:'

```
```
PHP Warning:  Undefined array key "filterTable" in D:\localhost_html\www9\vendor\ipub\websockets\src\Router\Route.php on line 610
PHP Fatal error:  Uncaught TypeError: array_flip(): Argument #1 ($array) must be of type array, null given in D:\localhost_html\www9\vendor\ipub\websockets\src\Router\Route.php:610
```

**Comment by akadlec** [comment]
@michalpixel můžeš to zkusit jen s jednou routou?

**Comment by michalpixel** [comment]
Ani to neslo.... pomohlo toto, jak mi vcera nekdo poradil na foru Nette:

Oba výskyty 
$meta['filterTable2'] = $meta[self::FILTER_TABLE] === [] ? null : array_flip($meta[self::FILTER_TABLE]);

v ipublikuj/websockets/src/Router/Route.php nahradit za 

$meta['filterTable2'] = ($meta[self::FILTER_TABLE] ?? []) === [] ? null : array_flip($meta[self::FILTER_TABLE]);

**Comment by akadlec** [comment]
tak jasně to je ošetření stavu, ale otázka je proč se to do toho stavu dostalo. Tuhle extension mám na projektu a tahle chyba nevyskočila. Můžeš zkusit ten druhý tvar routy? tedy aby to neřešilo replace? `'/notification' : 'Notification:'`

**Comment by michalpixel** [comment]
Pokud myslis druhym typem toto nize, tak to jsem tez zkousel a hazi to stejnou chybu... 
Jinak posledni verze Nette a PHP 8.2

services:
    - {class: App\RouterFactory, tags: [ipub.websockets.routes]}

**Comment by akadlec** [comment]
Aha, takže máš vlastní routerfactory?

**Comment by michalpixel** [comment]
Zkousel jsem obe moznosti a stejna chyba... ale hazi to chybu az kdyz tam je promenna v <>

`'/chat/<room>' : 'Chat:'` - CHYBA
'/notification' : 'Notification:' - pokud je tam jen tento radek, pak OK

**Comment by akadlec** [comment]
@michalpixel je to merged, takže si můžeš updatnout a zkusit

**Comment by rybajz** [comment]
Zdravíčko, mám stejný problém. Používám verzi 1.6.1. PHP 8.2
Mám routu:
webSockets:
	routes:
		'/chat/<chatId>' : 'Chat:'

PHP Warning: Undefined array key "filterTable" in /Users/rybajz/www/Know-how-klub/digi/vendor/ipub/websockets/src/Router/Route.php:610  @  CLI (PID: 31087): '' ipub:websockets:start 

Můžu poprosit o radu?

Moc díky

**Comment by akadlec** [comment]
Seš si jist že máš latest verzi?

**Comment by rybajz** [comment]
Dle composeru ano.
U sebe mám na řádku 610: 
$meta['filterTable2'] = ($meta[self::FILTER_TABLE] === [] || $meta[self::FILTER_TABLE] === null) ? null : array_flip($meta[self::FILTER_TABLE]);

a zde https://github.com/ipublikuj/websockets/blob/master/src/Router/Route.php je ten stejný kód
$meta['filterTable2'] = ($meta[self::FILTER_TABLE] === [] || $meta[self::FILTER_TABLE] === null) ? null : array_flip($meta[self::FILTER_TABLE]);

Jsem z toho zmaten:( původně jsem si myslel, že je to právě verzí

**Comment by akadlec** [comment]
@rybajz můžeš zkusit upadnout zda ti to půjde? (pokud to teda ještě používáš) Přidal jsem tam check navíc aby to necrashlo

**Comment by rybajz** [comment]
Ahoj,
díky moc. Zabralo to!
